sudo: required
dist: trusty

services:
  - docker

addons:
  chrome: stable

install:
  - sudo apt update -y
  - sudo apt install --only-upgrade docker-ce -y
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - (cd frontend && npm install)
  - docker build -t astrobin/astrobin:latest -f docker/astrobin.dockerfile .

before_script:
  - docker-compose -f docker/docker-compose.travis.yml up --no-deps -d
  - docker-compose -f docker/docker-compose.travis.yml exec astrobin ./scripts/init.sh

script:
  - (cd frontend; npm test)
  - (cd frontend; npm run e2e)
  - docker-compose -f docker/docker-compose.travis.yml exec astrobin ./scripts/test.sh

after_success:
  - docker cp -a .git $(docker ps -q -f name=astrobin_astrobin --last 1):/code # Needed by codecov.
  - docker-compose -f docker/docker-compose.travis.yml exec astrobin ./scripts/codecov.sh
  - docker push astrobin/astrobin:latest

after_script:
  - docker-compose -f docker/docker-compose.travis.yml down
  - docker logout

