sudo: required
dist: trusty

services:
  - docker


install:
  - docker build --no-cache -t astrobin/astrobin:latest -f docker/astrobin.dockerfile .

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - docker run -it astrobin/astrobin:latest ./scripts/test.sh
  - docker run -it astrobin/astrobin:latest bash -c (cd frontend; npm i && ng test)

after_success:
  #- docker cp -a .git $(docker ps -q -f name=astrobin_astrobin --last 1):/code # Needed by codecov.
  #- if [ ${DOCKER_MODE} = "compose" ]; then docker-compose -f docker/docker-compose.yml -f docker/docker-compose.build.yml -f docker/docker-compose.travis.yml exec astrobin ./scripts/codecov.sh; fi
  #- if [ ${DOCKER_MODE} = "stack" ]; then docker exec -it $(docker ps -q -f name=astrobin_astrobin --last 1) ./scripts/codecov.sh; fi
  - docker push astrobin/astrobin:latest

after_script:
  - docker logout

