version: '3'

services:
  celery_default:
    image: astrobin/astrobin:latest
    environment:
      - TESTING=true


  astrobin:
    image: astrobin/astrobin:latest
    environment:
      - TESTING=true
